# Site Settings
title: "Joao Barbosa"
name: "Joao Barbosa" 
description: "PI (INSERM) @ Neuromodulation Institute & NeuroSpin"
url: "https://jmourabarbosa.github.io"
baseurl: ""

# Author Settings
author:
  name: "Joao Barbosa"
  bio: "PI (INSERM) @ Neuromodulation Institute & NeuroSpin.<br>Neuroscientist in the making. Chronic emigrant."
  avatar: "/images/profile.png"
  email: "palerma@gmail.com"
  researchgate: "https://www.researchgate.net/profile/Joao_Barbosa43"
  bluesky: "jbarbosa.org"
  github: "jmourabarbosa"
  googlescholar: "https://scholar.google.es/citations?user=Q3-3_awAAAAJ&hl=en"
  orcid: "https://orcid.org/0000-0002-1907-3010"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author_profile: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md